#docker-compose -f docker-compose.yaml up
version: '3'
services:
    my-app:
        image: 436740495565.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
        ports:
          - "3000:3000"
        depends_on:
          - mongodb
    mongodb:
        image: mongo
        ports:
        - 27017:27017
        environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db      
    mongo-express:
        image: mongo-express
        ports:
        - 8080:8081
        depends_on:
            - mongodb
        environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
    mongo-data:
        driver: local